#!/usr/bin/env zsh

logit() {
	[ "$VERBOSE" = "TRUE" ] && echo "$@"
}
# setup our variables
zparseopts -A opts -myzsh: -module: -verbose
[ -n "$opts[--myzsh]" ] && export MYZSH="$opts[--myzsh]"
[ -n "$opts[--module]" ] && export MODULE="$opts[--module]"
export VERBOSE=FALSE
[ -n "$opts[--verbose]" ] && export VERBOSE="TRUE"

# if module isn't specified, check all of them
if [ -z "$MODULE" ]; then
	echo "nope: $MODULE"
	exit
	pushd $MYZSH/modules > /dev/null
	allmodules=(*)
	popd >/dev/null
	for m in $allmodules; do
		$0 --myzsh "$MYZSH" --module $m
	done
	exit
fi

echo "Testing myzsh from $MYZSH and module $MODULE"
echo

# check to see if $MYZSH is defined
[ -z "$MYZSH" ] && echo "\$MYZSH must be defined as the path to a checked out source" >&2 && exit 1

cd $MYZSH

# setup a sandbox directory to run our tests
SANDBOX=$(mktemp -d)
export ZDOTDIR="$SANDBOX"
cd "$SANDBOX"
echo "Using sandbox $SANDBOX"
echo

# copy tester script
cp "$MYZSH/tests/tester" "$SANDBOX/.zshrc"

# make special directories
for d in $MYZSH/tests/directories/*; do
	echo "Running $d"
	$d
	echo
done

zsh -i
exitcode=$?

rm -rf "$SANDBOX"
exit $exitcode
