#!zsh

logit() {
	[ "$VERBOSE" = "TRUE" ] && echo "$@"
}

show_prompt () {
	logit "Prompt:"
	logit "PROMPT: $PROMPT"
	logit "RPROMPT: $RPROMPT"
	logit
}

logit "=> Inside sandbox: $PWD"

# Setting variables for this test
ERRORFILE=/tmp/myzsh.test.errors.$$
THEME="null"
LPRIMARY=($MODULE)

logit "=> Sourcing myzsh"
source "$MYZSH/init" 2>"$ERRORFILE"

# Overriding theme
theme_prompt () {
	local i
	LPOUTPUT=""
	for ((i=1; i <= ${#lp_funcs}; i+=1)); do
		$lp_funcs[$i] | read OUTPUT
		[ -n "$OUTPUT" ] && LPOUTPUT+="$OUTPUT "
	done
	PROMPT="$LPOUTPUT"
}

logit "=> Themeing prompt"
theme_prompt 2>>"$ERRORFILE"
logit
logit "=> User arrays:"
logit "=> LPRIMARY: $LPRIMARY"
logit "=> RPRIMARY: $RPRIMARY"
logit "=> LSECONDARY: $LSECONDARY"
logit "=> RSECONDARY: $RSECONDARY"
logit
show_prompt
logit "Internal arrays:"
[ "$VERBOSE" = "TRUE" ] && set | grep -a _funcs=
logit

if [ -s "$ERRORFILE" ]; then
	echo "Errors Reported before directory tests"
	cat "$ERRORFILE"
	rm "$ERRORFILE"
	exit 1
fi

for d in *; do
	logit "Entering $d"
	pushd "$d" >/dev/null
	theme_prompt 2>"$ERRORFILE"
	show_prompt
	if [ -s "$ERRORFILE" ]; then
		echo "Errors Reported!"
		cat "$ERRORFILE"
		rm "$ERRORFILE"
		exit 1
	fi
	popd >/dev/null
done
rm "$ERRORFILE"

exit 0
